#!/usr/bin/env python3
"""Regenerate roster tables from live Sleeper data.

Two outputs, both for the team named TEAM_NAME:
  1. OPS-MANUAL.md — rewrites only the block between <!-- ROSTER:START -->
     and <!-- ROSTER:END -->. Everything else in the manual is left alone.
  2. docs/_data/roster.yml — one row per roster spot (slot, player, pos,
     team, status) that the public site's roster page renders.

Meant to run right after pull_sleeper.py (locally or in GitHub Actions).
"""

import json
import re
import sys
from pathlib import Path

from pull_sleeper import BASE, DATA_DIR, USERNAME, get, resolve_league, slim_players

TEAM_NAME = "Gradient Ascent"
ROOT = Path(__file__).resolve().parent.parent
MANUAL = ROOT / "OPS-MANUAL.md"
SITE_DATA = ROOT / "docs" / "_data" / "roster.yml"
START, END = "<!-- ROSTER:START -->", "<!-- ROSTER:END -->"

# Order the manual presents starters in (differs from Sleeper's TE/FLEX order)
SLOT_ORDER = ["QB", "RB", "RB", "WR", "WR", "FLEX", "TE", "K", "DEF"]
POS_RANK = {"QB": 0, "RB": 1, "WR": 2, "TE": 3, "K": 4, "DEF": 5}


def find_roster(league_id: str):
    users = get(f"{BASE}/league/{league_id}/users")
    rosters = get(f"{BASE}/league/{league_id}/rosters")
    owner = next((u for u in users if (u.get("metadata") or {}).get("team_name") == TEAM_NAME), None)
    if owner is None:  # team name unset in Sleeper -> fall back to Sean's account
        owner = next((u for u in users if u.get("display_name") == USERNAME), None)
    if owner is None:
        sys.exit(f"No team '{TEAM_NAME}' (or user {USERNAME}) in league {league_id}")
    uid = owner["user_id"]
    for r in rosters:
        if r.get("owner_id") == uid or uid in (r.get("co_owners") or []):
            return r
    sys.exit(f"No roster owned by {uid} in league {league_id}")


def load_players() -> dict:
    cache = DATA_DIR / "players_slim.json"
    if cache.exists():
        return json.loads(cache.read_text(encoding="utf-8"))
    return slim_players(get(f"{BASE}/players/nfl"))


def display_name(pid, players: dict) -> str:
    p = players.get(str(pid))
    if not p:
        return str(pid)
    name = p.get("name") or str(pid)
    if p.get("pos") == "DEF":  # "Buffalo Bills" -> "Buffalo", matching manual style
        name = name.rsplit(" ", 1)[0]
    return name


def roster_rows(roster: dict, roster_positions: list, players: dict) -> list:
    """[{slot, pid, player, pos, team, status}] in manual order: starters then bench."""
    starters = roster.get("starters") or []
    # Sleeper aligns starters[i] with roster_positions[i]; bucket by slot label
    by_slot: dict[str, list] = {}
    for slot, pid in zip(roster_positions, starters):
        if slot != "BN":
            by_slot.setdefault(slot, []).append(pid)

    def row(slot, pid):
        p = players.get(str(pid)) or {}
        empty = pid in (None, "0", 0)
        return {
            "slot": slot,
            "pid": None if empty else str(pid),
            "player": "—" if empty else display_name(pid, players),
            "pos": "" if empty else (p.get("pos") or ""),
            "team": "" if empty else (p.get("team") or "FA"),
            "status": "" if empty else (p.get("injury_status") or ""),
        }

    rows = []
    for slot in SLOT_ORDER:
        pid = by_slot.get(slot, []).pop(0) if by_slot.get(slot) else None
        rows.append(row(slot, pid))

    starter_ids = {str(s) for s in starters}
    bench_ids = [p for p in (roster.get("players") or []) if str(p) not in starter_ids]
    # Sleeper lists players in ID order; sort bench by position, then name
    bench_ids.sort(key=lambda p: (POS_RANK.get((players.get(str(p)) or {}).get("pos"), 9), display_name(p, players)))
    for i, pid in enumerate(bench_ids, 1):
        rows.append(row(f"BN{i}", pid))
    return rows


def build_table(rows: list) -> str:
    out = ["| Slot | Player |", "|------|--------|"]
    bench = []
    for r in rows:
        if r["slot"].startswith("BN"):
            bench.append(r["player"])
        else:
            out.append(f"| {r['slot']} | {r['player']} |")
    out.append(f"| BN | {', '.join(bench) if bench else '—'} |")
    return "\n".join(out)


def yaml_str(s: str) -> str:
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def build_site_data(rows: list) -> str:
    lines = ["# Generated by scripts/update_roster.py from Sleeper. Do not edit by hand;",
             "# it is overwritten after every data pull. Player notes live in notes.yml."]
    for r in rows:
        lines.append(f"- slot: {yaml_str(r['slot'])}")
        for k in ("player", "pos", "team", "status"):
            lines.append(f"  {k}: {yaml_str(r[k])}")
    return "\n".join(lines) + "\n"


def main():
    text = MANUAL.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END), re.DOTALL)
    if not pattern.search(text):
        sys.exit(f"{MANUAL.name}: missing {START} / {END} markers")

    _, league = resolve_league()
    roster = find_roster(league["league_id"])
    rows = roster_rows(roster, league.get("roster_positions") or [], load_players())

    table = build_table(rows)
    new_text = pattern.sub(lambda _m: f"{START}\n{table}\n{END}", text, count=1)
    if new_text == text:
        print("OK: roster table unchanged")
    else:
        MANUAL.write_text(new_text, encoding="utf-8")
        print(f"OK: updated roster table in {MANUAL.name}")

    SITE_DATA.parent.mkdir(parents=True, exist_ok=True)
    site = build_site_data(rows)
    if SITE_DATA.exists() and SITE_DATA.read_text(encoding="utf-8") == site:
        print("OK: docs/_data/roster.yml unchanged")
    else:
        SITE_DATA.write_text(site, encoding="utf-8")
        print("OK: wrote docs/_data/roster.yml")


if __name__ == "__main__":
    main()
